# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow_2d.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1435, 1169)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 9, 1411, 1101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.mainLayout1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.mainLayout1.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.mainLayout1.setContentsMargins(0, 0, 0, 0)
        self.mainLayout1.setObjectName("mainLayout1")
        self.mainLayout2 = QtWidgets.QGridLayout()
        self.mainLayout2.setObjectName("mainLayout2")
        self.initWidget = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.initWidget.setMaximumSize(QtCore.QSize(340, 16777215))
        self.initWidget.setObjectName("initWidget")
        self.initFrame = QtWidgets.QFrame(self.initWidget)
        self.initFrame.setGeometry(QtCore.QRect(10, 10, 331, 1001))
        self.initFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.initFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.initFrame.setObjectName("initFrame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.initFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 307, 981))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.depth_mean_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.depth_mean_box.setDecimals(0)
        self.depth_mean_box.setMaximum(98.0)
        self.depth_mean_box.setProperty("value", 5.0)
        self.depth_mean_box.setObjectName("depth_mean_box")
        self.horizontalLayout.addWidget(self.depth_mean_box, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sv_mean_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sv_mean_box.setDecimals(0)
        self.sv_mean_box.setMaximum(1000.0)
        self.sv_mean_box.setProperty("value", 20.0)
        self.sv_mean_box.setObjectName("sv_mean_box")
        self.horizontalLayout_5.addWidget(self.sv_mean_box, 0, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.sv_std_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sv_std_box.setDecimals(0)
        self.sv_std_box.setMaximum(1000.0)
        self.sv_std_box.setObjectName("sv_std_box")
        self.horizontalLayout_5.addWidget(self.sv_std_box, 0, QtCore.Qt.AlignHCenter)
        self.sv_unc_type = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.sv_unc_type.setObjectName("sv_unc_type")
        self.sv_unc_type.addItem("")
        self.sv_unc_type.addItem("")
        self.horizontalLayout_5.addWidget(self.sv_unc_type)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23, 0, QtCore.Qt.AlignHCenter)
        self.stress_type_box = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.stress_type_box.setObjectName("stress_type_box")
        self.stress_type_box.addItem("")
        self.stress_type_box.addItem("")
        self.stress_type_box.addItem("")
        self.verticalLayout.addWidget(self.stress_type_box, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.shmax_mean_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.shmax_mean_box.setDecimals(0)
        self.shmax_mean_box.setMaximum(1000.0)
        self.shmax_mean_box.setObjectName("shmax_mean_box")
        self.horizontalLayout_3.addWidget(self.shmax_mean_box, 0, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.shmax_std_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.shmax_std_box.setDecimals(0)
        self.shmax_std_box.setMaximum(1000.0)
        self.shmax_std_box.setObjectName("shmax_std_box")
        self.horizontalLayout_3.addWidget(self.shmax_std_box, 0, QtCore.Qt.AlignHCenter)
        self.shmax_unc_type = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.shmax_unc_type.setObjectName("shmax_unc_type")
        self.shmax_unc_type.addItem("")
        self.shmax_unc_type.addItem("")
        self.horizontalLayout_3.addWidget(self.shmax_unc_type)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.shmin_mean_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.shmin_mean_box.setDecimals(0)
        self.shmin_mean_box.setMaximum(1000.0)
        self.shmin_mean_box.setObjectName("shmin_mean_box")
        self.horizontalLayout_4.addWidget(self.shmin_mean_box, 0, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.shmin_std_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.shmin_std_box.setDecimals(0)
        self.shmin_std_box.setMaximum(1000.0)
        self.shmin_std_box.setObjectName("shmin_std_box")
        self.horizontalLayout_4.addWidget(self.shmin_std_box, 0, QtCore.Qt.AlignHCenter)
        self.shmin_unc_type = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.shmin_unc_type.setObjectName("shmin_unc_type")
        self.shmin_unc_type.addItem("")
        self.shmin_unc_type.addItem("")
        self.horizontalLayout_4.addWidget(self.shmin_unc_type)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.shmax_az_mean_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.shmax_az_mean_box.setDecimals(0)
        self.shmax_az_mean_box.setMaximum(360.0)
        self.shmax_az_mean_box.setObjectName("shmax_az_mean_box")
        self.horizontalLayout_6.addWidget(self.shmax_az_mean_box, 0, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.shmax_az_std_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.shmax_az_std_box.setDecimals(0)
        self.shmax_az_std_box.setObjectName("shmax_az_std_box")
        self.horizontalLayout_6.addWidget(self.shmax_az_std_box, 0, QtCore.Qt.AlignHCenter)
        self.az_unc_type = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.az_unc_type.setObjectName("az_unc_type")
        self.az_unc_type.addItem("")
        self.az_unc_type.addItem("")
        self.horizontalLayout_6.addWidget(self.az_unc_type)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.shmin_az_mean_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.shmin_az_mean_box.setDecimals(0)
        self.shmin_az_mean_box.setMaximum(360.0)
        self.shmin_az_mean_box.setObjectName("shmin_az_mean_box")
        self.horizontalLayout_7.addWidget(self.shmin_az_mean_box, 0, QtCore.Qt.AlignHCenter)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13, 0, QtCore.Qt.AlignHCenter)
        self.shmin_az_std_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.shmin_az_std_box.setDecimals(0)
        self.shmin_az_std_box.setObjectName("shmin_az_std_box")
        self.horizontalLayout_7.addWidget(self.shmin_az_std_box, 0, QtCore.Qt.AlignHCenter)
        self.az_unc_type2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.az_unc_type2.setObjectName("az_unc_type2")
        self.az_unc_type2.addItem("")
        self.az_unc_type2.addItem("")
        self.horizontalLayout_7.addWidget(self.az_unc_type2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.sv_inc_unc_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sv_inc_unc_box.setDecimals(0)
        self.sv_inc_unc_box.setProperty("value", 10.0)
        self.sv_inc_unc_box.setObjectName("sv_inc_unc_box")
        self.horizontalLayout_8.addWidget(self.sv_inc_unc_box, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.dip_mean_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.dip_mean_box.setDecimals(0)
        self.dip_mean_box.setProperty("value", 90.0)
        self.dip_mean_box.setObjectName("dip_mean_box")
        self.horizontalLayout_9.addWidget(self.dip_mean_box, 0, QtCore.Qt.AlignHCenter)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16, 0, QtCore.Qt.AlignHCenter)
        self.dip_std_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.dip_std_box.setDecimals(0)
        self.dip_std_box.setProperty("value", 10.0)
        self.dip_std_box.setObjectName("dip_std_box")
        self.horizontalLayout_9.addWidget(self.dip_std_box, 0, QtCore.Qt.AlignHCenter)
        self.dip_unc_type = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.dip_unc_type.setObjectName("dip_unc_type")
        self.dip_unc_type.addItem("")
        self.dip_unc_type.addItem("")
        self.horizontalLayout_9.addWidget(self.dip_unc_type, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.mu_mean_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.mu_mean_box.setMaximum(1.0)
        self.mu_mean_box.setSingleStep(0.1)
        self.mu_mean_box.setProperty("value", 0.6)
        self.mu_mean_box.setObjectName("mu_mean_box")
        self.horizontalLayout_10.addWidget(self.mu_mean_box, 0, QtCore.Qt.AlignRight)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18, 0, QtCore.Qt.AlignHCenter)
        self.mu_std_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.mu_std_box.setMaximum(1.0)
        self.mu_std_box.setSingleStep(0.05)
        self.mu_std_box.setProperty("value", 0.1)
        self.mu_std_box.setObjectName("mu_std_box")
        self.horizontalLayout_10.addWidget(self.mu_std_box, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.max_pf_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.max_pf_box.setProperty("value", 75.0)
        self.max_pf_box.setObjectName("max_pf_box")
        self.horizontalLayout_11.addWidget(self.max_pf_box, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22, 0, QtCore.Qt.AlignHCenter)
        self.hydro_gradient_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.hydro_gradient_box.setProperty("value", 10.0)
        self.hydro_gradient_box.setObjectName("hydro_gradient_box")
        self.verticalLayout.addWidget(self.hydro_gradient_box, 0, QtCore.Qt.AlignHCenter)
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fail_percentile_box = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.fail_percentile_box.setDecimals(0)
        self.fail_percentile_box.setProperty("value", 50.0)
        self.fail_percentile_box.setObjectName("fail_percentile_box")
        self.horizontalLayout_2.addWidget(self.fail_percentile_box, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.prob_model_yes = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.prob_model_yes.setObjectName("prob_model_yes")
        self.ModelButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.ModelButtonGroup.setObjectName("ModelButtonGroup")
        self.ModelButtonGroup.addButton(self.prob_model_yes)
        self.horizontalLayout_16.addWidget(self.prob_model_yes)
        self.det_model_yes = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.det_model_yes.setChecked(True)
        self.det_model_yes.setObjectName("det_model_yes")
        self.ModelButtonGroup.addButton(self.det_model_yes)
        self.horizontalLayout_16.addWidget(self.det_model_yes)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.stress_orient_widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.stress_orient_widget.setMinimumSize(QtCore.QSize(0, 250))
        self.stress_orient_widget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.stress_orient_widget.setObjectName("stress_orient_widget")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.stress_orient_widget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(9, 9, 291, 231))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.stress_orient_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.stress_orient_layout.setContentsMargins(0, 0, 0, 0)
        self.stress_orient_layout.setObjectName("stress_orient_layout")
        self.verticalLayout.addWidget(self.stress_orient_widget)
        self.mainLayout2.addWidget(self.initWidget, 0, 1, 1, 1)
        self.mainPlotWidget = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.mainPlotWidget.setObjectName("mainPlotWidget")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.mainPlotWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(9, 9, 1041, 1011))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.plotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setObjectName("plotLayout")
        self.mainLayout2.addWidget(self.mainPlotWidget, 0, 0, 1, 1)
        self.mainLayout1.addLayout(self.mainLayout2)
        self.executionWidget = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.executionWidget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.executionWidget.setObjectName("executionWidget")
        self.frame = QtWidgets.QFrame(self.executionWidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 1391, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 4, 1371, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_13.addWidget(self.label_20)
        self.shapefile_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.shapefile_edit.setObjectName("shapefile_edit")
        self.horizontalLayout_13.addWidget(self.shapefile_edit)
        self.file_browse_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.file_browse_button.setObjectName("file_browse_button")
        self.horizontalLayout_13.addWidget(self.file_browse_button)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_12.addWidget(self.line_2)
        self.executeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.executeButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.executeButton.setObjectName("executeButton")
        self.horizontalLayout_12.addWidget(self.executeButton)
        self.mainLayout1.addWidget(self.executionWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1435, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_json_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_json_file.setObjectName("actionOpen_json_file")
        self.actionSave_json_settings = QtWidgets.QAction(MainWindow)
        self.actionSave_json_settings.setObjectName("actionSave_json_settings")
        self.actionAdditional_Settings = QtWidgets.QAction(MainWindow)
        self.actionAdditional_Settings.setObjectName("actionAdditional_Settings")
        self.menuFile.addAction(self.actionOpen_json_file)
        self.menuFile.addAction(self.actionSave_json_settings)
        self.menuFile.addAction(self.actionAdditional_Settings)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Model Input Parameters"))
        self.label.setText(_translate("MainWindow", "Stress Observation Depth"))
        self.depth_mean_box.setSuffix(_translate("MainWindow", "  km"))
        self.label_8.setText(_translate("MainWindow", "Vertical Stress Gradient"))
        self.sv_mean_box.setSuffix(_translate("MainWindow", "  MPa/km"))
        self.label_9.setText(_translate("MainWindow", "+/-"))
        self.sv_unc_type.setItemText(0, _translate("MainWindow", "%"))
        self.sv_unc_type.setItemText(1, _translate("MainWindow", "MPa/km"))
        self.label_23.setText(_translate("MainWindow", "Stress Field Orientation"))
        self.stress_type_box.setItemText(0, _translate("MainWindow", "Reverse"))
        self.stress_type_box.setItemText(1, _translate("MainWindow", "Strike-Slip"))
        self.stress_type_box.setItemText(2, _translate("MainWindow", "Normal"))
        self.label_3.setText(_translate("MainWindow", "Maximum Horizontal Stress Gradient"))
        self.shmax_mean_box.setSuffix(_translate("MainWindow", "  MPa/km"))
        self.label_5.setText(_translate("MainWindow", "+/-"))
        self.shmax_unc_type.setItemText(0, _translate("MainWindow", "%"))
        self.shmax_unc_type.setItemText(1, _translate("MainWindow", "MPa/km"))
        self.label_6.setText(_translate("MainWindow", "Minimum Horizontal Stress Gradient"))
        self.shmin_mean_box.setSuffix(_translate("MainWindow", "  MPa/km"))
        self.label_7.setText(_translate("MainWindow", "+/-"))
        self.shmin_unc_type.setItemText(0, _translate("MainWindow", "%"))
        self.shmin_unc_type.setItemText(1, _translate("MainWindow", "MPa/km"))
        self.label_10.setText(_translate("MainWindow", "Maximum Horizontal Stress Azimuth"))
        self.shmax_az_mean_box.setSuffix(_translate("MainWindow", "  deg."))
        self.label_11.setText(_translate("MainWindow", "+/-"))
        self.az_unc_type.setItemText(0, _translate("MainWindow", "%"))
        self.az_unc_type.setItemText(1, _translate("MainWindow", "deg."))
        self.label_12.setText(_translate("MainWindow", "Minimum Horizontal Stress Azimuth"))
        self.shmin_az_mean_box.setSuffix(_translate("MainWindow", "  deg."))
        self.label_13.setText(_translate("MainWindow", "+/-"))
        self.az_unc_type2.setItemText(0, _translate("MainWindow", "%"))
        self.az_unc_type2.setItemText(1, _translate("MainWindow", "deg."))
        self.label_14.setText(_translate("MainWindow", "Vertical Stress Inclination Uncertainty"))
        self.sv_inc_unc_box.setSuffix(_translate("MainWindow", "  deg."))
        self.label_15.setText(_translate("MainWindow", "Dip Angle (right hand rule)"))
        self.dip_mean_box.setSuffix(_translate("MainWindow", "  deg. "))
        self.label_16.setText(_translate("MainWindow", "+/-"))
        self.dip_unc_type.setItemText(0, _translate("MainWindow", "%"))
        self.dip_unc_type.setItemText(1, _translate("MainWindow", "deg."))
        self.label_17.setText(_translate("MainWindow", "Fault Friction Coefficent [µ]"))
        self.label_18.setText(_translate("MainWindow", "+/-"))
        self.label_19.setText(_translate("MainWindow", "Pore Fluid Pressure Max [MPa]"))
        self.label_22.setText(_translate("MainWindow", "Hydrostatic Pressure Gradient [MPa/km]"))
        self.label_21.setText(_translate("MainWindow", "Failure Percentile Cutoff"))
        self.label_2.setText(_translate("MainWindow", "Model Mechanism"))
        self.prob_model_yes.setText(_translate("MainWindow", "Deterministic"))
        self.det_model_yes.setText(_translate("MainWindow", "Probabilistic"))
        self.label_20.setText(_translate("MainWindow", "Input Faults Shapefile"))
        self.file_browse_button.setText(_translate("MainWindow", "Browse"))
        self.executeButton.setText(_translate("MainWindow", "Run Model"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_json_file.setText(_translate("MainWindow", "Open json file"))
        self.actionSave_json_settings.setText(_translate("MainWindow", "Save json settings"))
        self.actionAdditional_Settings.setText(_translate("MainWindow", "Additional Settings"))
